### ISSUE TITLE
No package.json file in repo

### ISSUE THREAD

**Issue by ctaylo21** [nindalf/arewefastyet#2]
Hello! 

The instructions in the README will not work without a `package.json` file (the `npm install` command will fail). If you could add that to the repo, then others could contribute to the website. Thanks!

**Comment by avindra** [comment]
I think it might just be missing a `cd site` step

https://github.com/nindalf/arewefastyet/tree/master/site#getting-started

**Comment by ctaylo21** [comment]
Ah, my bad. I should have looked in those folders. Thanks!
